--
-- VHDL Architecture TSTE12_lab2_2009.Copy_of_VGA_Generate.behav
--
-- Created:
--          by - kentp.UNKNOWN (KENTSPC)
--          at - 19:06:21 2009-09-16
--
-- using Mentor Graphics HDL Designer(TM) 2008.1 (Build 17)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
LIBRARY altera_mf;
USE altera_mf.all;

ENTITY VGA_Generate IS
   PORT( 
      VGA_data    : IN     std_logic_vector (15 DOWNTO 0);
      pll_clk     : IN     std_logic;
      pll_reset_n : IN     std_logic;
      VGA_Address : OUT    std_logic_vector (19 DOWNTO 0);
      VGA_RD      : OUT    std_logic;
      VGA_lock    : OUT    std_logic;
      vga_b       : OUT    std_logic_vector (7 DOWNTO 0);
      vga_blank   : OUT    std_logic;
      vga_clk     : OUT    std_logic;
      vga_g       : OUT    std_logic_vector (7 DOWNTO 0);
      vga_r       : OUT    std_logic_vector (7 DOWNTO 0);
      vga_sync    : OUT    std_logic;
      vga_vs      : OUT    std_logic;
      vga_hs      : BUFFER std_logic
   );

-- Declarations

END VGA_Generate ;

--
ARCHITECTURE behav OF VGA_Generate IS

-- VHDL Entity TSTE12_lab2_2009.Copy_of_VGA_Generate.interface
--
-- Created:
--          by - kentp.UNKNOWN (KENTSPC)
--          at - 18:41:20 2009-09-16
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2008.1 (Build 17)
--

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL hblank    : std_logic;
   SIGNAL hcnt      : std_logic_vector(10 DOWNTO 0);
--   SIGNAL next_addr : std_logic;
   SIGNAL vblank    : std_logic;
   SIGNAL vcnt      : std_logic_vector(9 DOWNTO 0);

   -- Implicit buffer signal declarations
--   SIGNAL vga_clk_internal : std_logic;


BEGIN

   vga_sync <= '0';

  

--  next_addr <= NOT (hblank or vblank);

               
      process(pll_clk, pll_reset_n)
--        variable pixel_clk_tmp : std_logic;
        variable hcnt_val : UNSIGNED(10 downto 0);
        variable vcnt_val : UNSIGNED(9 downto 0);
        variable vga_hs_old : std_logic;
        variable vcnt_tmp : UNSIGNED(9 downto 0);
        variable vblank_old : std_logic;
--        variable odd_pixel : std_logic;
        variable VGA_Address_tmp : UNSIGNED(19 downto 0);
        variable hcnt_idx : UNSIGNED(10 downto 0);
        variable pixel_register : std_logic_vector(15 downto 0);
--        variable oddpixel_val : bit;
        variable vga_blank_new : std_logic;
        variable vga_blank_new1 : std_logic;
        variable vga_blank_new2 : std_logic;
        variable vga_blank_new3 : std_logic;
        variable vga_blank_new4 : std_logic;
        variable vga_blank_new5 : std_logic;
        begin
          vcnt_val := UNSIGNED(vcnt);
          hcnt_idx := UNSIGNED(hcnt);   -- simplify arithmetic expressions below
          if (pll_reset_n = '0') then
--            pixel_clk_tmp := '0';
            hcnt_val := (others => '0');
            vblank <= '0';
            vga_vs <= '1';
            vcnt_tmp := (others => '0');
            vga_hs_old := '0';
            VGA_Address_tmp := (others => '0');
            vblank_old := '0';
--            odd_pixel := '0';
            hblank <= '0';
            vga_hs <= '1';
            pixel_register := (others => '0');
--            oddpixel_val := '0';
            vga_r <= (others => '0');
            vga_g <= (others => '0');
            vga_b <= (others => '0');
            vga_blank <= '0';
            vga_blank_new := '0';
            vga_blank_new1 := '0';
            vga_blank_new2 := '0';
            vga_blank_new3 := '0';
            vga_blank_new4 := '0';
            vga_blank_new5 := '0';
          elsif rising_edge(pll_clk) then
--            pixel_clk_tmp := not pixel_clk_tmp;
--            if vga_clk_internal = '1' then
            if hcnt_val >= (1024+24+136+144-1) then
              hcnt_val := (others => '0');
            else
              hcnt_val := hcnt_val + 1;
            end if;
--            end if;
            if vcnt_val < 768 then
              vblank <= '0';
            else
              vblank <= '1';
            end if;
            if (vcnt_val >= 768+3) and (vcnt_val < (768+3+6)) then
              vga_vs <= '0';
            else
              vga_vs <= '1';
            end if;
            if (vga_hs_old = '1') and (vga_hs = '0') then
              if vcnt_tmp >= (768+3+6+29) then
                vcnt_tmp := (others => '0');
              else
                vcnt_tmp := vcnt_tmp + 1;
              end if;
            end if; 
            vga_hs_old := vga_hs;
--            if vga_clk_internal = '1' then
            if (vblank = '1') and (vblank_old = '0') then -- reset at start of vertical blank
              VGA_Address_tmp := (others => '0'); 
--                odd_pixel := '0';
            else
              if (vga_blank_new1 = '1') 
                --and (odd_pixel = '1') 
              then -- next address every other pixel
                  VGA_Address_tmp := VGA_Address_tmp + 1;
              end if;
--                odd_pixel := not odd_pixel;
            end if;
            vblank_old := vblank;
--              if odd_pixel = '0' then
            VGA_RD <= '1';
--              else
--                VGA_RD <= '0';
--              end if;
--            end if; 
            VGA_Address <= STD_LOGIC_VECTOR(VGA_Address_tmp);
            if (hcnt_idx >= 1024) then
              hblank <= '1';
            else
              hblank <= '0';
            end if;
            if (hcnt_idx > (1024+24)) and (hcnt_idx < (1024+24+136)) then
              vga_hs <= '0';
            else
              vga_hs <= '1';
            end if;
            if (hcnt_idx < (1024+8)) or (hcnt_idx > (1024+24+136+160-8)) then
              VGA_lock <= '1';
            else
              VGA_lock <= '0';
            end if;
--            if vga_clk_internal = '1' then
--              if oddpixel_val = '1' then
--                pixel_register (7 downto 0) := pixel_register(15 downto 8);
--              else
            pixel_register := VGA_data;
--              end if;
--              oddpixel_val := not oddpixel_val;
--            end if;
            vga_r <= pixel_register(15 downto 10) & "00";
            vga_g <= pixel_register(9 downto 5) & "000";
            vga_b <= pixel_register(4 downto 0) & "000";
            vga_blank <= vga_blank_new;
            vga_blank_new := vga_blank_new1;
--            vga_blank_new1 := vga_blank_new2;
--            vga_blank_new2 := vga_blank_new3;
--            vga_blank_new3 := vga_blank_new4;
--            vga_blank_new4 := vga_blank_new5;
            vga_blank_new1 := NOT( hblank OR vblank );
            hcnt <= STD_LOGIC_VECTOR(hcnt_val);
            vcnt <= STD_LOGIC_VECTOR(vcnt_tmp);
          end if;
--          vga_clk_internal <= pixel_clk_tmp; 
        end process;

   -- Implicit buffered output assignments
   vga_clk <= not pll_clk;

END ARCHITECTURE behav;

